<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PutridParrot.Distributed.Postgresql\PutridParrot.Distributed.Postgresql.csproj" />
    <ProjectReference Include="..\PutridParrot.Distributed.Redis\PutridParrot.Distributed.Redis.csproj" />
    <ProjectReference Include="..\PutridParrot.Distributed.SqlServer\PutridParrot.Distributed.SqlServer.csproj" />
    <ProjectReference Include="..\PutridParrot.Distributed\PutridParrot.Distributed\PutridParrot.Distributed.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="appsettings.Development.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
